#!/usr/bin/env python3
"""Generate reproducible shuffled pointer chains without guest initialization."""
from pathlib import Path
import random

NODES = 1280
indices = list(range(NODES))
random.Random(0xB1AC2026).shuffle(indices)
lines = ["/* Generated by generate_dependent_stream_data.py; do not edit.",
         " * One shuffled 1280-node cycle, partitioned into 2 or 4 disjoint segments.",
         " * Golden cursors are read only after the measured execution. */",
         "#define STREAM_DATA_NODES 1280",
         "static const volatile struct node measured_nodes[1280]",
         "  __attribute__((aligned(4096), used)) = {"]
for step, physical in enumerate(indices):
    successor = indices[(step + 1) % NODES]
    lines.append(f"  [{physical}] = {{ &measured_nodes[{successor}], {step + 1}, {{0}} }},")
lines += ["};"]
for streams in [2, 4]:
    lines += [f"static const volatile struct node *const measured_heads_{streams}[{streams}]",
              "  __attribute__((aligned(64))) = { " +
              ", ".join(f"&measured_nodes[{indices[s * (NODES // streams)]}]" for s in range(streams)) + " };"]
lines += ["static const volatile struct node *const expected_cursors[1280] = {"]
for first in range(0, NODES, 8):
    lines.append("    " + ", ".join(f"&measured_nodes[{p}]" for p in indices[first:first+8]) + ",")
lines += ["};", "static const volatile struct node warm_nodes[16]",
          "  __attribute__((aligned(4096), used)) = {"]
for step in range(16):
    lines.append(f"  {{ &warm_nodes[{(step + 1) % 16}], {step + 1}, {{0}} }},")
lines += ["};", "static const volatile struct node *const warm_heads_2[2]",
          "  __attribute__((aligned(64))) = { &warm_nodes[0], &warm_nodes[8] };",
          "static const volatile struct node *const warm_heads_4[4]",
          "  __attribute__((aligned(64))) = { &warm_nodes[0], &warm_nodes[4],",
          "                                     &warm_nodes[8], &warm_nodes[12] };", ""]
Path(__file__).with_name("dependent_stream_data.h").write_text("\n".join(lines))
