#!/usr/bin/env python3
"""Generate reproducible shuffled pointer chains without guest initialization."""
from pathlib import Path
import random

NODES = 1280
WARM_NODES = 40
STREAM_COUNTS = (2, 4, 10)
indices = list(range(NODES))
random.Random(0xB1AC2026).shuffle(indices)
lines = ["/* Generated by generate_dependent_stream_data.py; do not edit.",
         " * One shuffled 1280-node cycle, partitioned into 2, 4 or 10 disjoint segments.",
         " * Golden cursors are read only after the measured execution. */",
         "#define STREAM_DATA_NODES 1280",
         f"#define STREAM_WARM_NODES {WARM_NODES}",
         "static const volatile struct node measured_nodes[1280]",
         "  __attribute__((aligned(4096), used)) = {"]
for step, physical in enumerate(indices):
    successor = indices[(step + 1) % NODES]
    lines.append(f"  [{physical}] = {{ &measured_nodes[{successor}], {step + 1}, {{0}} }},")
lines += ["};"]
for streams in STREAM_COUNTS:
    lines += [f"static const volatile struct node *const measured_heads_{streams}[{streams}]",
              "  __attribute__((aligned(64))) = { " +
              ", ".join(f"&measured_nodes[{indices[s * (NODES // streams)]}]" for s in range(streams)) + " };"]
lines += ["static const volatile struct node *const expected_cursors[1280] = {"]
for first in range(0, NODES, 8):
    lines.append("    " + ", ".join(f"&measured_nodes[{p}]" for p in indices[first:first+8]) + ",")
lines += ["};", f"static const volatile struct node warm_nodes[{WARM_NODES}]",
          "  __attribute__((aligned(4096), used)) = {"]
for step in range(WARM_NODES):
    lines.append(f"  {{ &warm_nodes[{(step + 1) % WARM_NODES}], {step + 1}, {{0}} }},")
lines += ["};"]
for streams in STREAM_COUNTS:
    lines += [f"static const volatile struct node *const warm_heads_{streams}[{streams}]",
              "  __attribute__((aligned(64))) = { " +
              ", ".join(f"&warm_nodes[{s * (WARM_NODES // streams)}]" for s in range(streams)) + " };"]
lines += [""]
Path(__file__).with_name("dependent_stream_data.h").write_text("\n".join(lines))
